config/routes.rb
Tastebud::Application.routes.draw do

  resources :restaurants do
    resources :reviews
  end

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  root to: "home#index"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :address1, :address2, :city, :name, :other_comments, :phone, :state, :zip
  has_many :reviews

  validates :name, :presence => true
  validates :address1, :presence => true
  validates :city, :presence => true
  validate :phone, :length => { :is => 5}, :allow_blank => true

  def self.search(search, page)
    if search
      where('name ILIKE ? or city ILIKE ? or address1 ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%").paginate(:page => page, :per_page => 10)
    else
      self.paginate(:page => page, :per_page => 10).order('id DESC')
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base

  attr_accessible :comment, :rating, :restaurant_id, :user_id

  belongs_to :user
  belongs_to :restaurant

  validate :rating, :presence => true
  validate :restaurant_id, :presence => true
  validate :user_id, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  respond_to :html, :js

  before_filter :authenticate_user!

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])
    @restaurant.save
    respond_to do |format|
      format.js 
    end
  end

  def index
    @restaurants = Restaurant.search(params[:search], params[:page])
    respond_to do |format|    
      if request.xhr?
        format.js
      else 
        format.html 
      end
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    respond_with @restaurant
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  respond_to :html, :js

  before_filter :authenticate_user!

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews.paginate(:page => params[:page], :per_page => 10).order('id DESC')
    respond_to do |format|
      if request.xhr?
        format.js
      else
        format.html
      end
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.find(params[:id])
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /reviews/1/edit
  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.find(params[:id])
  end


  def create
    @restaurant = Restaurant.new(params[:restaurant])
    @restaurant.save
    respond_to do |format|
      format.js
    end
  end


  # POST /reviews
  # POST /reviews.json
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.create(params[:review])
    @review.save
    respond_to do |format|
      format.js
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.erb
<div class="home_page_text">
  <h3> Hi! Welcome to Tastebud! A website where you can see what other
        people think about restaurants.
  </h3>
  <p>
    Here's how it works. Click <a class="links" href="<%= url_for(:action => 'index', :controller => 'restaurants') %>"><b>here</b></a>
    to view a listing of all restaurants users have talked about on this website. Search for restaurants by name or city. 
    Or create one if it doesn't exist!
  </p>
  <p>
    See what other people are saying and post reviews. You need to be a member of the site to view/submit reviews.
  </p>
  <p>
    Have fun! Happy browsing!
  </p>
  <p>
    Tastebud team.
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tastebud</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="centered">
  <div id="banner">
    <img src="/assets/banner.jpg" /> 
  </div>
  <div id="user_now">
    <% if user_signed_in? %>
      Welcome <%= current_user.email %>, Not this user?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete  %>
    <% else %>
           <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
    <% end %>
  </div>
  <div>
    <%= link_to (image_tag 'home.png', :class => 'home_link'), root_url %>
  </div>
  <br />
<% flash.each do |name, msg| %>
   <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

<div id="footer">
  <p align=center>
     Site developed as part of coursework for COSC 630 by Akshatha Raj (araj0@frostburg.edu)
  </p>
</div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tastebud</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="centered">
  <div id="banner">
    <img src="/assets/banner.jpg" />
  </div>
  <div id="user_now">
    <% if user_signed_in? %>
      Welcome <%= current_user.email %>, Not this user?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete  %>
    <% else %>
           <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
    <% end %>
  </div>
  <div>
    <%= link_to (image_tag 'home.png', :class => 'home_link'), root_url %>
  </div>
  <br />
<% flash.each do |name, msg| %>
   <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<div class="objectdetail">
  <%= yield %>
</div>
</body>
</html>

app/views/restaurants/_new.html.erb
  <br />
  <h1> Please enter restaurant information </h1>
  <br />
  <%= form_for @restaurant, :html => {:id => 'add_restaurant_form'}, :remote => true do |f| -%>
       <label>Name:</label> <%= f.text_field :name %> <br />
       <label>Phone:</label> <%= f.text_field :phone %> <br />
       <label>Address Line 1:</label> <%= f.text_field :address1 %> <br />
       <label>Address Line 2:</label> <%= f.text_field :address2 %> <br />
       <label>City:</label> <%= f.text_field :city %> <br /> 
       <label>Zip:</label> <%= f.text_field :zip %> <br /> 
       <label>State:</label> <%= f.text_field :state %> <br /> 
       <label>Comments:</label> <%= f.text_field :other_comments %> <br /> 
       <%= f.submit %>
  <% end -%>
   <br />

app/views/restaurants/_restaurant_paging.html.erb
  <% @restaurants.each do |restaurant| %>
    <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%=h restaurant.phone  %></td>
        <td><%=h restaurant.address1 %></td>
        <td><%=h restaurant.city    %></td>
        <td><%=h restaurant.state  %></td>
        <td><%=h restaurant.zip %></td>
    </tr>
  <% end %>

app/views/restaurants/_restaurant_row.html.erb
<tr>
  <td>
    <%= link_to @restaurant.name, @restaurant  %>
  </td>
  <td> 
    <%=h @restaurant.phone %> 
  </td>
  <td> 
    <%=h @restaurant.address1 %> 
  </td>
  <td> 
    <%=h @restaurant.city %> 
  </td>
  <td> 
    <%=h @restaurant.state %> 
  </td>
  <td> 
    <%=h @restaurant.zip %> 
  </td>
</tr>

app/views/restaurants/_restaurant_search_hits.html.erb
  <thead>
    <tr>
        <th>Name     </th>
        <th>Phone    </th>
        <th>Address </th>
        <th>City     </th>
        <th>State    </th>
        <th>Zip      </th>
    </tr>
  </thead>
  <tbody>
  <% @restaurants.each do |restaurant| %>
    <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%=h restaurant.phone  %></td>
        <td><%=h restaurant.address1 %></td>
        <td><%=h restaurant.city    %></td>
        <td><%=h restaurant.state  %></td>
        <td><%=h restaurant.zip %></td>
    </tr>
  <% end %>
  </tbody>

app/views/restaurants/_search.html.erb
<%= form_tag restaurants_path, :method => 'get', :html => {:id => 'search_restaurant_form'}, :remote => true do %>
  <%= text_field_tag :search, params[:search], :id => 'search_field', :placeholder => 'Start typing name, address or city to filter' %>
<% end %>

app/views/restaurants/_search_results.html.erb
<h1>Restaurant Search Results</h1>

<table class="hovertable">
    <tr>
        <th>Name     </th>
        <th>Phone    </th>
        <th>Address </th>
        <th>City     </th>
        <th>State    </th>
        <th>Zip      </th>
    </tr>

<% @restaurants.each do |restaurant| %>
    <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%=h restaurant.phone  %></td>
        <td><%=h restaurant.address1 %></td>
        <td><%=h restaurant.city    %></td>
        <td><%=h restaurant.state  %></td>
        <td><%=h restaurant.zip %></td>
    </tr>
<% end %>
</table>

<br />

<a href="<%= url_for(:action => 'new', :controller => 'restaurants') %>"> Don't see the restaurant listed? Add it! </a>
<br />

app/views/restaurants/create.js.erb
$("#restaurant_listing tbody").prepend("<%= escape_javascript(render :partial => "restaurant_row", :locals => { :restaurant => @restaurant } ) %>");

app/views/restaurants/index.html.erb
<%= javascript_include_tag "restaurants" %>
<h1 class="listing_heading">Restaurant Listing</h1>
<div id="search">
  <%= render :partial => 'restaurants/search' %>
</div>

<table id="restaurant_listing">
  <thead>
    <tr>
        <th>Name     </th>
        <th>Phone    </th>
        <th>Address </th>
        <th>City     </th>
        <th>State    </th>
        <th>Zip      </th>
    </tr>
  </thead>
  <tbody>
  <% @restaurants.each do |restaurant| %>
    <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%=h restaurant.phone  %></td>
        <td><%=h restaurant.address1 %></td>
        <td><%=h restaurant.city    %></td>
        <td><%=h restaurant.state  %></td>
        <td><%=h restaurant.zip %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br />
<a class="links" href="#" id="add_new"> Don't see the restaurant listed? Add it! </a>
<br />

<div class="add_restaurant">
  <%= render "new", :@restaurant => Restaurant.new %>
</div>

app/views/restaurants/index.js.erb
<% if params[:search] %>
  $("#restaurant_listing").html("<%= escape_javascript(render :partial => "restaurant_search_hits", :locals => { :restaurants => @restaurants } ) %>");
<% end %>

<% if params[:page] %>
  $("#restaurant_listing").append("<%= escape_javascript(render :partial => "restaurant_paging", :locals => { :restaurants => @restaurants } ) %>");
<% end %>

app/views/restaurants/new.html.erb
<div class="user_review">
  <h1> Please enter restaurant information </h1>
  <br />
  <%= form_for @restaurant do |f| -%>
       <label>Name:</label> <%= f.text_field :name %> <br />
       <label>Phone:</label> <%= f.text_field :phone %> <br />
       <label>Address Line 1:</label> <%= f.text_field :address1 %> <br />
       <label>Address Line 2:</label> <%= f.text_field :address2 %> <br />
       <label>City:</label> <%= f.text_field :city %> <br /> 
       <label>Zip:</label> <%= f.text_field :zip %> <br /> 
       <label>State:</label> <%= f.text_field :state %> <br /> 
       <label>Comments:</label> <%= f.text_field :other_comments %> <br /> 
       <%= f.submit %>
  <% end -%>
   <br />
   <a href="<%= url_for(:action => 'index', :controller => 'restaurants') %>"> Back to Restaurant Listing </a>
   <br/>
</div>

app/views/restaurants/show.html.erb
<div class="objectdetail">
  <h1><%= @restaurant.name %></h1>
  <p><strong>Phone: </strong> <%= @restaurant.phone %><br />
   <%= @restaurant.address1 %>
   <%= @restaurant.address2 %><br />
   <%= @restaurant.city %>
   <%= @restaurant.state %>
   <%= @restaurant.zip %><br />
   <br />
   <a class="links" id="view_reviews" href="#"> View Reviews </a>

   <div id="reviews_listing">
      <%= render "reviews/index", :@reviews => @restaurant.reviews.paginate(:page => params[:page], :per_page => 10).order('id DESC') %>
   </div>
   <a class="links" href="<%= url_for(:action => 'index', :controller => 'restaurants') %>"> Back to full restaurant listing </a>   
</div>

app/views/reviews/_form.html.erb
<%= form_for [@restaurant, @review], :html => {:id => 'add_review_form'}, :remote => true do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :restaurant_id, :value => @restaurant.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.select( :rating, options_for_select([['Certainly Not worth a second visit', 1], ['Average food and service', 2], 
                            ['Good food, worth the money', 3], ['Definitely going back again', 4],
                            ['Best restaurant I have eaten at', 5]])) %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area(:comment, :size => '50x10') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_index.html.erb
<%= javascript_include_tag "reviews" %>
<div class="user_review">
  <h3> User Reviews </h3>
  <div id="restaurant_reviews">
  <% @reviews.each do |review| %>
    <p> submitted by 
      <%= review.user.email %> on 
      <%= review.created_at %> <br />
      Rating: <%= review.rating %>(out of 5 stars) <br />
      Comment: <%= review.comment %>
    </p>
  <hr>
  <% end %>
  </div>
  <br />
</div>

<a class="links" id="add_review" href="<%= url_for(:action => 'new', :controller => 'reviews', :restaurant_id => @restaurant.id) %>"> Submit your review </a>

<br />

<div id="new_review">
 <%= render "reviews/new", :@review => Review.new %>
</div>

app/views/reviews/_new.html.erb
  <h1>How do you like <%= @restaurant.name %>? </h1>

  <%= render 'reviews/form' %>

app/views/reviews/_review_row.html.erb
<p> submitted by 
      <%= @review.user.email %> on 
      <%= @review.created_at %> <br />
      Rating: <%= @review.rating %>(out of 5 stars) <br />
      Comment: <%= @review.comment %>
</p>
<hr>

app/views/reviews/_reviews_paging.html.erb
  <% @reviews.each do |review| %>
    <p> submitted by
      <%= review.user.email %> on
      <%= review.created_at %> <br />
      Rating: <%= review.rating %>(out of 5 stars) <br />
      Comment: <%= review.comment %>
    </p>
  <hr>
  <% end %>

app/views/reviews/create.js.erb
$("#restaurant_reviews").prepend("<%= escape_javascript(render :partial => "review_row", :locals => { :restaurant => @restaurant, :review => @review } ) %>");

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |

app/views/reviews/index.html.erb
<div class="user_review">
  <h1> User Reviews </h1> <br />   

  <% @reviews.each do |review| %>
    <p> submitted by 
      <%= review.user.email %> on 
      <%= review.created_at %> <br />
      Rating: <%= review.rating %>(out of 5 stars) <br />
      Comment: <%= review.comment %>
    </p>
  <hr>
  <% end %>
  <br />
  <%= will_paginate @reviews %>
  <br />
  <a href="<%= url_for(:action => 'new', :controller => 'reviews', :restaurant_id => @restaurant.id) %>"> Add Review </a>
  <br />
  <a href="<%= url_for(:action => 'show', :controller => 'restaurants', :id => @restaurant.id) %>"> Back </a>
  <br />
</div>

app/views/reviews/index.js.erb
$("#restaurant_reviews").append("<%= escape_javascript(render :partial => "reviews_paging", :locals => { :reviews => @reviews } ) %>");

app/views/reviews/show.html.erb
<div class="user_review">
  <p id="notice"><%= notice %></p>

  <h1>
    <%= @review.restaurant.name %>
  </h1>

  <p> by 
    <%= @review.user.email %>
  </p>

  <p>
    <b>Rating:</b> <%= @review.rating %>(out of 5 stars)
  </p>

  <p>
    <b>Comment:</b>
    <%= @review.comment %>
  </p>
   <a href="<%= url_for(:action => 'index', :controller => 'reviews', :restaurant_id => @restaurant.id) %>"> View all reviews for <%= @review.restaurant.name %></a>
   <br />
   <a href="<%= url_for(:action => 'index', :controller => 'restaurants') %>"> Back to Restaurant Listing </a>
   <br />
</div>